# Generated by Django 3.0.4 on 2020-03-18 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=20)),
                ('rate_average', models.CharField(max_length=50)),
                ('publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=200)),
                ('rate', models.IntegerField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='theArchiveDB_app.Libro')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='theArchiveDB_app.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.IntegerField()),
                ('comment', models.ManyToManyField(related_name='_update_comment_+', through='theArchiveDB_app.Comment', to='theArchiveDB_app.Usuario')),
                ('total_votes', models.ManyToManyField(related_name='_update_total_votes_+', to='theArchiveDB_app.Usuario')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='theArchiveDB_app.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='libro',
            name='estanteria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theArchiveDB_app.Usuario'),
        ),
        migrations.AddField(
            model_name='libro',
            name='valoration',
            field=models.ManyToManyField(related_name='_libro_valoration_+', through='theArchiveDB_app.Valoracion', to='theArchiveDB_app.Usuario'),
        ),
        migrations.CreateModel(
            name='Estanteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('puntuation', models.FloatField()),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='theArchiveDB_app.Libro')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='theArchiveDB_app.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='update_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='theArchiveDB_app.Update'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='theArchiveDB_app.Usuario'),
        ),
        migrations.CreateModel(
            name='Challange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_book', models.IntegerField()),
                ('actual_book', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='theArchiveDB_app.Usuario')),
            ],
        ),
    ]
